/*
COPYRIGHT BENJAMIN ISHERWOOD 23/10/2014
THIS SOFTWARE IS INTENDED FOR OPEN SOURCE USE, REDISTRIBUTION
IS ENCOURAGE

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
OTHER DEALINGS IN THE SOFTWARsE.
*/
#ifndef TILE_H
#define TILE_H

#include "engineStdafx.h"
#include "WorldObject2D.h"

class Tile : public WorldObject2D
{
	private:
		Uint imageIndex;
	protected:
		friend World2D;
		Tile(void);
		Tile(ULong id, string name, string desc, Uint textureIndex, bool pass);
		Tile(ULong id, string name, string desc, Uint textureIndex);
		Uint getImageIndex(void) const;
		void moveCoords(void);
};

#endif